version: "3.9"

services:
  cpu:
    image: coedl/vad-sli-asr:21.05
    volumes:
      - ${PWD}:/workspace
    working_dir: /workspace
    entrypoint:
      - /bin/bash
    stdin_open: true
    tty: true

  gpu:
    image: coedl/vad-sli-asr:21.05
    volumes:
      - ${PWD}:/workspace
    working_dir: /workspace
    entrypoint:
      - /bin/bash
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
